# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake

# The command to remove a file.
RM = /Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/john/Desktop/workspace/github-2020/fdfs-cli/fdfs-cli

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/john/Desktop/workspace/github-2020/fdfs-cli/fdfs-cli

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/john/Desktop/workspace/github-2020/fdfs-cli/fdfs-cli/CMakeFiles /Users/john/Desktop/workspace/github-2020/fdfs-cli/fdfs-cli/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/john/Desktop/workspace/github-2020/fdfs-cli/fdfs-cli/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named fdfs_cli

# Build rule for target.
fdfs_cli: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fdfs_cli
.PHONY : fdfs_cli

# fast build rule for target.
fdfs_cli/fast:
	$(MAKE) -f CMakeFiles/fdfs_cli.dir/build.make CMakeFiles/fdfs_cli.dir/build
.PHONY : fdfs_cli/fast

common/fdfs_define.o: common/fdfs_define.c.o

.PHONY : common/fdfs_define.o

# target to build an object file
common/fdfs_define.c.o:
	$(MAKE) -f CMakeFiles/fdfs_cli.dir/build.make CMakeFiles/fdfs_cli.dir/common/fdfs_define.c.o
.PHONY : common/fdfs_define.c.o

common/fdfs_define.i: common/fdfs_define.c.i

.PHONY : common/fdfs_define.i

# target to preprocess a source file
common/fdfs_define.c.i:
	$(MAKE) -f CMakeFiles/fdfs_cli.dir/build.make CMakeFiles/fdfs_cli.dir/common/fdfs_define.c.i
.PHONY : common/fdfs_define.c.i

common/fdfs_define.s: common/fdfs_define.c.s

.PHONY : common/fdfs_define.s

# target to generate assembly for a file
common/fdfs_define.c.s:
	$(MAKE) -f CMakeFiles/fdfs_cli.dir/build.make CMakeFiles/fdfs_cli.dir/common/fdfs_define.c.s
.PHONY : common/fdfs_define.c.s

common/fdfs_global.o: common/fdfs_global.c.o

.PHONY : common/fdfs_global.o

# target to build an object file
common/fdfs_global.c.o:
	$(MAKE) -f CMakeFiles/fdfs_cli.dir/build.make CMakeFiles/fdfs_cli.dir/common/fdfs_global.c.o
.PHONY : common/fdfs_global.c.o

common/fdfs_global.i: common/fdfs_global.c.i

.PHONY : common/fdfs_global.i

# target to preprocess a source file
common/fdfs_global.c.i:
	$(MAKE) -f CMakeFiles/fdfs_cli.dir/build.make CMakeFiles/fdfs_cli.dir/common/fdfs_global.c.i
.PHONY : common/fdfs_global.c.i

common/fdfs_global.s: common/fdfs_global.c.s

.PHONY : common/fdfs_global.s

# target to generate assembly for a file
common/fdfs_global.c.s:
	$(MAKE) -f CMakeFiles/fdfs_cli.dir/build.make CMakeFiles/fdfs_cli.dir/common/fdfs_global.c.s
.PHONY : common/fdfs_global.c.s

hello/MyHello.o: hello/MyHello.c.o

.PHONY : hello/MyHello.o

# target to build an object file
hello/MyHello.c.o:
	$(MAKE) -f CMakeFiles/fdfs_cli.dir/build.make CMakeFiles/fdfs_cli.dir/hello/MyHello.c.o
.PHONY : hello/MyHello.c.o

hello/MyHello.i: hello/MyHello.c.i

.PHONY : hello/MyHello.i

# target to preprocess a source file
hello/MyHello.c.i:
	$(MAKE) -f CMakeFiles/fdfs_cli.dir/build.make CMakeFiles/fdfs_cli.dir/hello/MyHello.c.i
.PHONY : hello/MyHello.c.i

hello/MyHello.s: hello/MyHello.c.s

.PHONY : hello/MyHello.s

# target to generate assembly for a file
hello/MyHello.c.s:
	$(MAKE) -f CMakeFiles/fdfs_cli.dir/build.make CMakeFiles/fdfs_cli.dir/hello/MyHello.c.s
.PHONY : hello/MyHello.c.s

hello/Other.o: hello/Other.c.o

.PHONY : hello/Other.o

# target to build an object file
hello/Other.c.o:
	$(MAKE) -f CMakeFiles/fdfs_cli.dir/build.make CMakeFiles/fdfs_cli.dir/hello/Other.c.o
.PHONY : hello/Other.c.o

hello/Other.i: hello/Other.c.i

.PHONY : hello/Other.i

# target to preprocess a source file
hello/Other.c.i:
	$(MAKE) -f CMakeFiles/fdfs_cli.dir/build.make CMakeFiles/fdfs_cli.dir/hello/Other.c.i
.PHONY : hello/Other.c.i

hello/Other.s: hello/Other.c.s

.PHONY : hello/Other.s

# target to generate assembly for a file
hello/Other.c.s:
	$(MAKE) -f CMakeFiles/fdfs_cli.dir/build.make CMakeFiles/fdfs_cli.dir/hello/Other.c.s
.PHONY : hello/Other.c.s

main.o: main.c.o

.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) -f CMakeFiles/fdfs_cli.dir/build.make CMakeFiles/fdfs_cli.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i

.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) -f CMakeFiles/fdfs_cli.dir/build.make CMakeFiles/fdfs_cli.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s

.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) -f CMakeFiles/fdfs_cli.dir/build.make CMakeFiles/fdfs_cli.dir/main.c.s
.PHONY : main.c.s

test/gen_files/gen_files.o: test/gen_files/gen_files.c.o

.PHONY : test/gen_files/gen_files.o

# target to build an object file
test/gen_files/gen_files.c.o:
	$(MAKE) -f CMakeFiles/fdfs_cli.dir/build.make CMakeFiles/fdfs_cli.dir/test/gen_files/gen_files.c.o
.PHONY : test/gen_files/gen_files.c.o

test/gen_files/gen_files.i: test/gen_files/gen_files.c.i

.PHONY : test/gen_files/gen_files.i

# target to preprocess a source file
test/gen_files/gen_files.c.i:
	$(MAKE) -f CMakeFiles/fdfs_cli.dir/build.make CMakeFiles/fdfs_cli.dir/test/gen_files/gen_files.c.i
.PHONY : test/gen_files/gen_files.c.i

test/gen_files/gen_files.s: test/gen_files/gen_files.c.s

.PHONY : test/gen_files/gen_files.s

# target to generate assembly for a file
test/gen_files/gen_files.c.s:
	$(MAKE) -f CMakeFiles/fdfs_cli.dir/build.make CMakeFiles/fdfs_cli.dir/test/gen_files/gen_files.c.s
.PHONY : test/gen_files/gen_files.c.s

tracker/fdfs_server_id_func.o: tracker/fdfs_server_id_func.c.o

.PHONY : tracker/fdfs_server_id_func.o

# target to build an object file
tracker/fdfs_server_id_func.c.o:
	$(MAKE) -f CMakeFiles/fdfs_cli.dir/build.make CMakeFiles/fdfs_cli.dir/tracker/fdfs_server_id_func.c.o
.PHONY : tracker/fdfs_server_id_func.c.o

tracker/fdfs_server_id_func.i: tracker/fdfs_server_id_func.c.i

.PHONY : tracker/fdfs_server_id_func.i

# target to preprocess a source file
tracker/fdfs_server_id_func.c.i:
	$(MAKE) -f CMakeFiles/fdfs_cli.dir/build.make CMakeFiles/fdfs_cli.dir/tracker/fdfs_server_id_func.c.i
.PHONY : tracker/fdfs_server_id_func.c.i

tracker/fdfs_server_id_func.s: tracker/fdfs_server_id_func.c.s

.PHONY : tracker/fdfs_server_id_func.s

# target to generate assembly for a file
tracker/fdfs_server_id_func.c.s:
	$(MAKE) -f CMakeFiles/fdfs_cli.dir/build.make CMakeFiles/fdfs_cli.dir/tracker/fdfs_server_id_func.c.s
.PHONY : tracker/fdfs_server_id_func.c.s

tracker/fdfs_shared_func.o: tracker/fdfs_shared_func.c.o

.PHONY : tracker/fdfs_shared_func.o

# target to build an object file
tracker/fdfs_shared_func.c.o:
	$(MAKE) -f CMakeFiles/fdfs_cli.dir/build.make CMakeFiles/fdfs_cli.dir/tracker/fdfs_shared_func.c.o
.PHONY : tracker/fdfs_shared_func.c.o

tracker/fdfs_shared_func.i: tracker/fdfs_shared_func.c.i

.PHONY : tracker/fdfs_shared_func.i

# target to preprocess a source file
tracker/fdfs_shared_func.c.i:
	$(MAKE) -f CMakeFiles/fdfs_cli.dir/build.make CMakeFiles/fdfs_cli.dir/tracker/fdfs_shared_func.c.i
.PHONY : tracker/fdfs_shared_func.c.i

tracker/fdfs_shared_func.s: tracker/fdfs_shared_func.c.s

.PHONY : tracker/fdfs_shared_func.s

# target to generate assembly for a file
tracker/fdfs_shared_func.c.s:
	$(MAKE) -f CMakeFiles/fdfs_cli.dir/build.make CMakeFiles/fdfs_cli.dir/tracker/fdfs_shared_func.c.s
.PHONY : tracker/fdfs_shared_func.c.s

tracker/fdfs_trackerd.o: tracker/fdfs_trackerd.c.o

.PHONY : tracker/fdfs_trackerd.o

# target to build an object file
tracker/fdfs_trackerd.c.o:
	$(MAKE) -f CMakeFiles/fdfs_cli.dir/build.make CMakeFiles/fdfs_cli.dir/tracker/fdfs_trackerd.c.o
.PHONY : tracker/fdfs_trackerd.c.o

tracker/fdfs_trackerd.i: tracker/fdfs_trackerd.c.i

.PHONY : tracker/fdfs_trackerd.i

# target to preprocess a source file
tracker/fdfs_trackerd.c.i:
	$(MAKE) -f CMakeFiles/fdfs_cli.dir/build.make CMakeFiles/fdfs_cli.dir/tracker/fdfs_trackerd.c.i
.PHONY : tracker/fdfs_trackerd.c.i

tracker/fdfs_trackerd.s: tracker/fdfs_trackerd.c.s

.PHONY : tracker/fdfs_trackerd.s

# target to generate assembly for a file
tracker/fdfs_trackerd.c.s:
	$(MAKE) -f CMakeFiles/fdfs_cli.dir/build.make CMakeFiles/fdfs_cli.dir/tracker/fdfs_trackerd.c.s
.PHONY : tracker/fdfs_trackerd.c.s

tracker/tracker_func.o: tracker/tracker_func.c.o

.PHONY : tracker/tracker_func.o

# target to build an object file
tracker/tracker_func.c.o:
	$(MAKE) -f CMakeFiles/fdfs_cli.dir/build.make CMakeFiles/fdfs_cli.dir/tracker/tracker_func.c.o
.PHONY : tracker/tracker_func.c.o

tracker/tracker_func.i: tracker/tracker_func.c.i

.PHONY : tracker/tracker_func.i

# target to preprocess a source file
tracker/tracker_func.c.i:
	$(MAKE) -f CMakeFiles/fdfs_cli.dir/build.make CMakeFiles/fdfs_cli.dir/tracker/tracker_func.c.i
.PHONY : tracker/tracker_func.c.i

tracker/tracker_func.s: tracker/tracker_func.c.s

.PHONY : tracker/tracker_func.s

# target to generate assembly for a file
tracker/tracker_func.c.s:
	$(MAKE) -f CMakeFiles/fdfs_cli.dir/build.make CMakeFiles/fdfs_cli.dir/tracker/tracker_func.c.s
.PHONY : tracker/tracker_func.c.s

tracker/tracker_global.o: tracker/tracker_global.c.o

.PHONY : tracker/tracker_global.o

# target to build an object file
tracker/tracker_global.c.o:
	$(MAKE) -f CMakeFiles/fdfs_cli.dir/build.make CMakeFiles/fdfs_cli.dir/tracker/tracker_global.c.o
.PHONY : tracker/tracker_global.c.o

tracker/tracker_global.i: tracker/tracker_global.c.i

.PHONY : tracker/tracker_global.i

# target to preprocess a source file
tracker/tracker_global.c.i:
	$(MAKE) -f CMakeFiles/fdfs_cli.dir/build.make CMakeFiles/fdfs_cli.dir/tracker/tracker_global.c.i
.PHONY : tracker/tracker_global.c.i

tracker/tracker_global.s: tracker/tracker_global.c.s

.PHONY : tracker/tracker_global.s

# target to generate assembly for a file
tracker/tracker_global.c.s:
	$(MAKE) -f CMakeFiles/fdfs_cli.dir/build.make CMakeFiles/fdfs_cli.dir/tracker/tracker_global.c.s
.PHONY : tracker/tracker_global.c.s

tracker/tracker_mem.o: tracker/tracker_mem.c.o

.PHONY : tracker/tracker_mem.o

# target to build an object file
tracker/tracker_mem.c.o:
	$(MAKE) -f CMakeFiles/fdfs_cli.dir/build.make CMakeFiles/fdfs_cli.dir/tracker/tracker_mem.c.o
.PHONY : tracker/tracker_mem.c.o

tracker/tracker_mem.i: tracker/tracker_mem.c.i

.PHONY : tracker/tracker_mem.i

# target to preprocess a source file
tracker/tracker_mem.c.i:
	$(MAKE) -f CMakeFiles/fdfs_cli.dir/build.make CMakeFiles/fdfs_cli.dir/tracker/tracker_mem.c.i
.PHONY : tracker/tracker_mem.c.i

tracker/tracker_mem.s: tracker/tracker_mem.c.s

.PHONY : tracker/tracker_mem.s

# target to generate assembly for a file
tracker/tracker_mem.c.s:
	$(MAKE) -f CMakeFiles/fdfs_cli.dir/build.make CMakeFiles/fdfs_cli.dir/tracker/tracker_mem.c.s
.PHONY : tracker/tracker_mem.c.s

tracker/tracker_proto.o: tracker/tracker_proto.c.o

.PHONY : tracker/tracker_proto.o

# target to build an object file
tracker/tracker_proto.c.o:
	$(MAKE) -f CMakeFiles/fdfs_cli.dir/build.make CMakeFiles/fdfs_cli.dir/tracker/tracker_proto.c.o
.PHONY : tracker/tracker_proto.c.o

tracker/tracker_proto.i: tracker/tracker_proto.c.i

.PHONY : tracker/tracker_proto.i

# target to preprocess a source file
tracker/tracker_proto.c.i:
	$(MAKE) -f CMakeFiles/fdfs_cli.dir/build.make CMakeFiles/fdfs_cli.dir/tracker/tracker_proto.c.i
.PHONY : tracker/tracker_proto.c.i

tracker/tracker_proto.s: tracker/tracker_proto.c.s

.PHONY : tracker/tracker_proto.s

# target to generate assembly for a file
tracker/tracker_proto.c.s:
	$(MAKE) -f CMakeFiles/fdfs_cli.dir/build.make CMakeFiles/fdfs_cli.dir/tracker/tracker_proto.c.s
.PHONY : tracker/tracker_proto.c.s

tracker/tracker_relationship.o: tracker/tracker_relationship.c.o

.PHONY : tracker/tracker_relationship.o

# target to build an object file
tracker/tracker_relationship.c.o:
	$(MAKE) -f CMakeFiles/fdfs_cli.dir/build.make CMakeFiles/fdfs_cli.dir/tracker/tracker_relationship.c.o
.PHONY : tracker/tracker_relationship.c.o

tracker/tracker_relationship.i: tracker/tracker_relationship.c.i

.PHONY : tracker/tracker_relationship.i

# target to preprocess a source file
tracker/tracker_relationship.c.i:
	$(MAKE) -f CMakeFiles/fdfs_cli.dir/build.make CMakeFiles/fdfs_cli.dir/tracker/tracker_relationship.c.i
.PHONY : tracker/tracker_relationship.c.i

tracker/tracker_relationship.s: tracker/tracker_relationship.c.s

.PHONY : tracker/tracker_relationship.s

# target to generate assembly for a file
tracker/tracker_relationship.c.s:
	$(MAKE) -f CMakeFiles/fdfs_cli.dir/build.make CMakeFiles/fdfs_cli.dir/tracker/tracker_relationship.c.s
.PHONY : tracker/tracker_relationship.c.s

tracker/tracker_status.o: tracker/tracker_status.c.o

.PHONY : tracker/tracker_status.o

# target to build an object file
tracker/tracker_status.c.o:
	$(MAKE) -f CMakeFiles/fdfs_cli.dir/build.make CMakeFiles/fdfs_cli.dir/tracker/tracker_status.c.o
.PHONY : tracker/tracker_status.c.o

tracker/tracker_status.i: tracker/tracker_status.c.i

.PHONY : tracker/tracker_status.i

# target to preprocess a source file
tracker/tracker_status.c.i:
	$(MAKE) -f CMakeFiles/fdfs_cli.dir/build.make CMakeFiles/fdfs_cli.dir/tracker/tracker_status.c.i
.PHONY : tracker/tracker_status.c.i

tracker/tracker_status.s: tracker/tracker_status.c.s

.PHONY : tracker/tracker_status.s

# target to generate assembly for a file
tracker/tracker_status.c.s:
	$(MAKE) -f CMakeFiles/fdfs_cli.dir/build.make CMakeFiles/fdfs_cli.dir/tracker/tracker_status.c.s
.PHONY : tracker/tracker_status.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... fdfs_cli"
	@echo "... common/fdfs_define.o"
	@echo "... common/fdfs_define.i"
	@echo "... common/fdfs_define.s"
	@echo "... common/fdfs_global.o"
	@echo "... common/fdfs_global.i"
	@echo "... common/fdfs_global.s"
	@echo "... hello/MyHello.o"
	@echo "... hello/MyHello.i"
	@echo "... hello/MyHello.s"
	@echo "... hello/Other.o"
	@echo "... hello/Other.i"
	@echo "... hello/Other.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... test/gen_files/gen_files.o"
	@echo "... test/gen_files/gen_files.i"
	@echo "... test/gen_files/gen_files.s"
	@echo "... tracker/fdfs_server_id_func.o"
	@echo "... tracker/fdfs_server_id_func.i"
	@echo "... tracker/fdfs_server_id_func.s"
	@echo "... tracker/fdfs_shared_func.o"
	@echo "... tracker/fdfs_shared_func.i"
	@echo "... tracker/fdfs_shared_func.s"
	@echo "... tracker/fdfs_trackerd.o"
	@echo "... tracker/fdfs_trackerd.i"
	@echo "... tracker/fdfs_trackerd.s"
	@echo "... tracker/tracker_func.o"
	@echo "... tracker/tracker_func.i"
	@echo "... tracker/tracker_func.s"
	@echo "... tracker/tracker_global.o"
	@echo "... tracker/tracker_global.i"
	@echo "... tracker/tracker_global.s"
	@echo "... tracker/tracker_mem.o"
	@echo "... tracker/tracker_mem.i"
	@echo "... tracker/tracker_mem.s"
	@echo "... tracker/tracker_proto.o"
	@echo "... tracker/tracker_proto.i"
	@echo "... tracker/tracker_proto.s"
	@echo "... tracker/tracker_relationship.o"
	@echo "... tracker/tracker_relationship.i"
	@echo "... tracker/tracker_relationship.s"
	@echo "... tracker/tracker_status.o"
	@echo "... tracker/tracker_status.i"
	@echo "... tracker/tracker_status.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

